CREATE TABLE IF NOT EXISTS packageSubscriptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  packageId INTEGER NOT NULL,
  orderId INTEGER,
  isActive INTEGER NOT NULL DEFAULT 1,
  startDate TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
  endDate TEXT,
  renewalDueDate TEXT,
  autoRenew INTEGER NOT NULL DEFAULT 0,
  createdAt TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
);
