import { Link } from 'wouter';

export function TermsOfServiceEn() {
  return (
    <>
      <h2 className="text-xl font-bold text-gray-900">1. Definitions</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li><strong>The Academy:</strong> XFlex Academy, including all affiliated platforms (website, Telegram, WhatsApp, educational platforms, AI tools such as Lex AI).</li>
        <li><strong>User / Subscriber:</strong> Any person who registers, subscribes, or uses any of the Academy's services.</li>
        <li><strong>Content:</strong> Includes educational materials, videos, recommendations, analyses, tools, messages, and newsletters.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">2. Nature of Services Provided</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>All services provided are educational and informational only.</li>
        <li>The Academy does not provide personal investment advice or portfolio management.</li>
        <li>Any recommendations or analyses are general educational opinions and not direct instructions to buy or sell.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">3. Trading & Loss Disclaimer</h2>
      <p>Trading in financial markets involves high risk and may result in partial or total loss of capital.</p>
      <p className="font-semibold">The user acknowledges and agrees that:</p>
      <ul className="list-disc ps-6 space-y-1">
        <li>All trading decisions made are entirely their personal responsibility.</li>
        <li>The Academy, its team, trainers, or tools (including Lex AI) are not responsible for any financial losses.</li>
      </ul>
      <p className="font-semibold">The Academy bears no responsibility for:</p>
      <ul className="list-disc ps-6 space-y-1">
        <li>Losses resulting from poor capital management.</li>
        <li>Incorrect use of recommendations.</li>
        <li>Trading during news events or abnormal market conditions.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">4. Lex AI (Artificial Intelligence Tool)</h2>
      <p>Lex AI is an assistive analysis tool and not an automated trading system or profit guarantee.</p>
      <p className="font-semibold">Results generated by Lex AI:</p>
      <ul className="list-disc ps-6 space-y-1">
        <li>Are based on historical data and analytical algorithms.</li>
        <li>Do not guarantee complete accuracy or success.</li>
      </ul>
      <p>Use of Lex AI is solely at the user's own risk.</p>

      <h2 className="text-xl font-bold text-gray-900">5. No Profit Guarantee</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>The Academy does not guarantee any profits.</li>
        <li>Any figures, examples, or past results are displayed for educational purposes only and do not imply the same results will be achieved in the future.</li>
        <li>Past performance does not necessarily reflect future performance.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">6. User's Personal Commitment</h2>
      <p className="font-semibold">The user is responsible for:</p>
      <ul className="list-disc ps-6 space-y-1">
        <li>Ensuring trading is suitable for their financial situation.</li>
        <li>Not trading with funds they cannot afford to lose.</li>
        <li>Adhering to the recommended risk management practices.</li>
      </ul>
      <p>Using the Academy's services for any illegal purposes is prohibited.</p>

      <h2 className="text-xl font-bold text-gray-900">7. Intellectual Property</h2>
      <p>All content provided is the exclusive intellectual property of XFlex Academy.</p>
      <p className="font-semibold">It is prohibited to:</p>
      <ul className="list-disc ps-6 space-y-1">
        <li>Copy the content.</li>
        <li>Republish it.</li>
        <li>Sell or share it with third parties.</li>
      </ul>
      <p>Any violation exposes the offender to legal accountability.</p>

      <h2 className="text-xl font-bold text-gray-900">8. Subscription & Payment Policy</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>All subscriptions are non-refundable after activation.</li>
        <li>The user is responsible for choosing the appropriate plan before payment.</li>
        <li>Any temporary service interruption due to technical maintenance, updates, or force majeure does not constitute grounds for a refund claim.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">9. Account Suspension or Termination</h2>
      <p className="font-semibold">The Academy reserves the right to suspend or cancel any user's subscription without prior notice in the event of:</p>
      <ul className="list-disc ps-6 space-y-1">
        <li>Misuse of content.</li>
        <li>Spreading misleading information.</li>
        <li>Abuse towards the Academy or its team.</li>
      </ul>
      <p>No financial obligation towards the user arises from such suspension.</p>

      <h2 className="text-xl font-bold text-gray-900">10. Limitation of Legal Liability</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>The maximum potential liability of the Academy (if any) shall not exceed the value of the subscription paid.</li>
        <li>The Academy is not responsible for internet outages, issues with external platforms (broker, trading platform, banks, digital wallets), or decisions of third parties.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">11. Confidentiality & Data Protection</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>The Academy is committed to maintaining the confidentiality of user data.</li>
        <li>Data is not shared with any third party unless legally required or with the user's consent.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">12. Amendments to Terms</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>The Academy reserves the right to modify the terms and conditions at any time.</li>
        <li>Continued use of services after modification constitutes implicit acceptance of the new terms.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">13. Governing Law</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>These terms are governed by the applicable laws of Palestine.</li>
        <li>Any dispute shall be resolved amicably; failing that, it shall be referred to the competent judicial authorities.</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900">14. Acceptance</h2>
      <p className="font-semibold">By using any of XFlex Academy's services, you:</p>
      <ul className="list-disc ps-6 space-y-1">
        <li>Acknowledge that you have read these terms.</li>
        <li>Fully understand them.</li>
        <li>Agree to them without reservation.</li>
      </ul>

      <div className="mt-8 p-4 bg-emerald-50 rounded-lg border border-emerald-200">
        <p className="font-semibold text-gray-900">📋 Subscription & Refund Policy</p>
        <p>To view the full subscription and refund policy, please visit:</p>
        <Link href="/refund-policy">
          <span className="text-emerald-600 hover:underline cursor-pointer font-medium">Refund Policy →</span>
        </Link>
      </div>
    </>
  );
}
