import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  en: {
    // Header/Navigation
    'nav.myCourses': 'My Courses',
    'nav.lexai': 'LexAI',
    'nav.adminPanel': 'Admin Panel',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    
    // Homepage
    'home.hero.title': 'Master Trading with',
    'home.hero.subtitle': 'Expert Guidance',
    'home.hero.description': 'Learn from industry experts and take your trading skills to the next level with our comprehensive courses. Start your journey to financial freedom today.',
    'home.hero.browseCourses': 'Browse Courses',
    'home.hero.startTrial': 'Start Free Trial',
    'home.hero.activeStudents': 'Active Students',
    'home.hero.expertCourses': 'Expert Courses',
    'home.hero.rating': 'Rating',
    
    'home.cta.title': 'Get Started Today',
    'home.cta.subtitle': 'Join thousands of successful traders',
    'home.cta.email': 'Enter your email',
    'home.cta.password': 'Choose a password',
    'home.cta.createAccount': 'Create Free Account',
    'home.cta.haveAccount': 'Already have an account?',
    'home.cta.signIn': 'Sign in',
    'home.cta.guarantee': '30-day money-back guarantee',
    
    'home.why.title': 'Why Choose XFlex Academy?',
    'home.why.subtitle': 'Everything you need to become a successful trader in one place',
    'home.why.expertCourses': 'Expert-Led Courses',
    'home.why.expertDesc': 'Learn from experienced traders with proven track records in the markets',
    'home.why.practicalStrategies': 'Practical Strategies',
    'home.why.practicalDesc': 'Apply real-world trading strategies that work in today\'s markets',
    'home.why.lifetimeAccess': 'Lifetime Access',
    'home.why.lifetimeDesc': 'Get unlimited access to course materials and future updates',
    
    'home.courses.title': 'Available Courses',
    'home.courses.subtitle': 'Choose from our selection of trading courses designed for all skill levels',
    'home.courses.noCourses': 'No courses available yet. Check back soon!',
    
    // Services Section
    'home.services.title': 'Our Services',
    'home.services.subtitle': 'Everything you need to succeed in Forex trading',
    
    // Course Card
    'home.service.course.title': 'Trading Courses',
    'home.service.course.desc': 'Learn Forex trading from basics to advanced strategies with comprehensive video courses.',
    'home.service.course.f1': 'Complete Trading Course',
    'home.service.course.f2': 'Price Action Strategies',
    'home.service.course.f3': 'Risk Management',
    'home.service.course.f4': 'Technical Analysis',
    'home.service.course.cta': 'Activate Course Access',
    'home.service.course.price': 'One-Time Payment',
    
    // Recommendations Card
    'home.service.rec.title': 'Recommendations Group',
    'home.service.rec.desc': 'Live trading signals from expert analysts with real-time alerts and email notifications.',
    'home.service.rec.f1': 'Live Trading Signals',
    'home.service.rec.f2': 'Expert Analyst Posts',
    'home.service.rec.f3': 'Email Alerts on New Signals',
    'home.service.rec.f4': 'Interactive Reactions',
    'home.service.rec.cta': 'Subscribe Now',
    'home.service.rec.price': '$100 / month',
    
    // LexAI Card
    'home.service.lexai.title': 'LexAI Assistant',
    'home.service.lexai.desc': 'Get AI-powered chart analysis and trading recommendations powered by advanced AI.',
    'home.service.lexai.f1': 'Multi-timeframe Analysis',
    'home.service.lexai.f2': 'Support & Resistance Levels',
    'home.service.lexai.f3': 'Entry & Exit Points',
    'home.service.lexai.f4': 'Risk Management Tips',
    'home.service.lexai.cta': 'Activate LexAI (30 Days)',
    'home.service.lexai.price': '$30 / month',
    
    // Already Registered
    'home.alreadyRegistered': 'Already Registered?',
    'home.loginHere': 'Login Here',
    
    // Contact Support
    'home.contact.title': 'Contact Support',
    'home.contact.subtitle': 'Have a question? Send us a message and we\'ll get back to you.',
    'home.contact.email': 'Your Email',
    'home.contact.emailPlaceholder': 'email@example.com',
    'home.contact.message': 'Your Message',
    'home.contact.messagePlaceholder': 'How can we help you?',
    'home.contact.send': 'Send Message',
    'home.contact.sending': 'Sending...',
    'home.contact.sent': 'Message sent! We\'ll get back to you soon.',
    
    'home.footer.tagline': 'Empowering traders worldwide with expert knowledge and practical skills',
    'home.footer.rights': 'All rights reserved.',
    
    // Dashboard
    'dashboard.title': 'Welcome back, {name}!',
    'dashboard.subtitle': 'Continue your learning journey',
    'dashboard.settings': 'Settings',
    'dashboard.logout': 'Logout',
    'dashboard.loading': 'Loading your dashboard...',
    'dashboard.signInTitle': 'Welcome to XFlex Trading Academy',
    'dashboard.signInDesc': 'Please sign in to access your learning dashboard',
    'dashboard.signInBtn': 'Sign In to Continue',
    'dashboard.stats.totalCourses': 'Total Courses',
    'dashboard.stats.enrolledLabel': 'Enrolled courses',
    'dashboard.stats.enrolledCourses': 'Enrolled Courses',
    'dashboard.stats.courses': 'active courses',
    'dashboard.stats.completedCourses': 'Completed',
    'dashboard.stats.finished': 'Finished courses',
    'dashboard.stats.inProgress': 'In Progress',
    'dashboard.stats.activeLearning': 'Active learning',
    'dashboard.stats.avgProgress': 'Avg. Progress',
    'dashboard.stats.overallCompletion': 'Overall completion',
    'dashboard.stats.quizzesPassed': 'Quizzes Passed',
    'dashboard.stats.levels': 'quiz levels completed',
    'dashboard.enrolledCourses.title': 'My Courses',
    'dashboard.enrolledCourses.description': 'Continue learning and track your progress',
    'dashboard.noCoursesEnrolled': 'You haven\'t enrolled in any courses yet',
    'dashboard.noCoursesTitle': 'No courses yet',
    'dashboard.noCoursesDesc': 'Start learning by enrolling in a course',
    'dashboard.browseCourses': 'Browse Courses',
    'dashboard.completed': 'Completed',
    'dashboard.episodes': 'episodes',
    'dashboard.episodesCompleted': 'episodes completed',
    'dashboard.progress': 'Progress',
    'dashboard.continue': 'Continue Learning',
    'dashboard.review': 'Review Course',
    'dashboard.myAccess': 'My Access',
    'dashboard.myAccessDesc': 'Your course access and LexAI status are linked to your email.',
    'dashboard.courseAccess': 'Course',
    'dashboard.lexaiAccess': 'LexAI',
    'dashboard.recAccess': 'Recommendations',
    'dashboard.active': 'Active',
    'dashboard.notActive': 'Not active',
    'dashboard.openCourses': 'Open Courses',
    'dashboard.openLexai': 'Open LexAI',
    'dashboard.openRec': 'Open Recommendations',
    'dashboard.activateRec': 'Activate Recommendations',
    'dashboard.nav.home': 'Home',
    'dashboard.nav.dashboard': 'My Dashboard',
    'dashboard.nav.quizzes': 'Quizzes',
    'dashboard.nav.lexai': 'LexAI',
    'dashboard.nav.rec': 'Recommendations Group',
    'dashboard.nav.support': 'Support',
    'dashboard.quickActions.browseMore': 'Discover More',
    'dashboard.quickActions.discoverNewCourses': 'Explore more trading courses and expand your knowledge',
    'dashboard.quickActions.browseCourses': 'Browse All Courses',
    'dashboard.quickActions.aiAssistant': 'FlexAI Assistant',
    'dashboard.quickActions.getAIHelp': 'Get instant help from our AI trading assistant',
    'dashboard.quickActions.openChat': 'Open Chat',
    
    // LexAI
    'lexai.title': 'LexAI - AI Currency Analysis',
    'lexai.subscribe.title': 'Subscribe to LexAI',
    'lexai.subscribe.desc': 'Get AI-powered currency analysis and trading recommendations',
    'lexai.subscribe.price': '$29.99/month',
    'lexai.subscribe.feature1': '100 chart analyses per month',
    'lexai.subscribe.feature2': 'Real-time market insights',
    'lexai.subscribe.feature3': 'Trading recommendations',
    'lexai.subscribe.feature4': 'Technical analysis reports',
    'lexai.subscribe.button': 'Subscribe Now',
    'lexai.chat.title': 'Chat with LexAI',
    'lexai.chat.remaining': 'analyses remaining this month',
    'lexai.chat.placeholder': 'Ask about currency analysis or upload a chart image...',
    'lexai.chat.send': 'Send',
    'lexai.chat.uploadImage': 'Upload Chart Image',
    'lexai.chat.uploading': 'Uploading...',
    
    // Admin Sidebar
    'admin.sidebar.overview': 'Overview',
    'admin.sidebar.dashboard': 'Dashboard',
    'admin.sidebar.content': 'Content',
    'admin.sidebar.courses': 'Courses',
    'admin.sidebar.courseKeys': 'Course Keys',
    'admin.sidebar.quizzes': 'Quizzes',
    'admin.sidebar.quizDashboard': 'Dashboard',
    'admin.sidebar.quizUsers': 'User Progress',
    'admin.sidebar.quizQuestions': 'Questions',
    'admin.sidebar.lexai': 'LexAI',
    'admin.sidebar.conversations': 'Conversations',
    'admin.sidebar.subscriptions': 'Subscriptions',
    'admin.sidebar.lexaiKeys': 'LexAI Keys',
    'admin.sidebar.users': 'Users',
    'admin.sidebar.usersList': 'All Users',
    'admin.sidebar.enrollments': 'Enrollments',
    'admin.sidebar.recommendations': 'Recommendations',
    'admin.sidebar.groupMgmt': 'Group Management',
    'admin.sidebar.support': 'Support & Staff',
    'admin.sidebar.supportChat': 'Support Chat',
    'admin.sidebar.supportDash': 'Support Dashboard',
    'admin.sidebar.staffPortal': 'Staff Portal',
    'admin.sidebar.roles': 'Roles',
    'admin.sidebar.analytics': 'Analytics',
    'admin.sidebar.settings': 'Settings',
    'admin.sidebar.signOut': 'Sign Out',

    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.dashboard.welcome': 'Welcome to Admin Panel',
    'admin.dashboard.subtitle': 'Manage your platform from here',
    'admin.totalUsers': 'Total Users',
    'admin.totalCourses': 'Total Courses',
    'admin.activeEnrollments': 'Active Enrollments',
    'admin.totalRevenue': 'Total Revenue',
    'admin.dashboard.registeredStudents': 'Registered students',
    'admin.dashboard.publishedCourses': 'Published courses',
    'admin.dashboard.activeSubs': 'Active Subscriptions',
    'admin.dashboard.keys': 'Course Registration Keys',
    'admin.dashboard.manageKeys': 'Manage Keys',
    'admin.dashboard.courses': 'Courses',
    'admin.dashboard.viewCourses': 'View Courses',
    'admin.dashboard.users': 'Users',
    'admin.dashboard.viewUsers': 'View Users',
    'admin.dashboard.recentEnrollments': 'Recent Enrollments',
    'admin.dashboard.noEnrollments': 'No enrollments yet',
    'admin.dashboard.enrolled': 'Enrolled',
    'admin.dashboard.quickActions': 'Quick Actions',

    // Admin Courses
    'admin.courses': 'Courses',
    'admin.courses.subtitle': 'Manage your trading courses',
    'admin.courses.addCourse': 'Add Course',
    'admin.courses.noCourses': 'No courses yet.',
    'admin.courses.manageEpisodes': 'Manage Episodes',
    'admin.courses.edit': 'Edit',
    'admin.courses.editCourse': 'Edit Course',
    'admin.courses.createCourse': 'Create New Course',
    'admin.courses.fillBoth': 'Fill course details in English and Arabic',
    'admin.courses.titleEn': 'Title (English)',
    'admin.courses.titleAr': 'Title (Arabic)',
    'admin.courses.descEn': 'Description (English)',
    'admin.courses.descAr': 'Description (Arabic)',
    'admin.courses.price': 'Price (USD)',
    'admin.courses.level': 'Level',
    'admin.courses.status': 'Status',
    'admin.courses.thumbnail': 'Thumbnail URL',
    'admin.courses.beginner': 'Beginner',
    'admin.courses.intermediate': 'Intermediate',
    'admin.courses.advanced': 'Advanced',
    'admin.courses.draft': 'Draft',
    'admin.courses.published': 'Published',
    'admin.courses.save': 'Save Course',
    'admin.courses.cancel': 'Cancel',
    'admin.courses.episodes': 'episodes',

    // Admin Episodes
    'admin.episodes': 'Episodes',
    'admin.episodes.backToCourses': 'Back to Courses',
    'admin.episodes.subtitle': 'Manage course episodes',
    'admin.episodes.addEpisode': 'Add Episode',
    'admin.episodes.noEpisodes': 'No episodes yet',
    'admin.episodes.createFirst': 'Create First Episode',
    'admin.episodes.free': 'FREE',
    'admin.episodes.videoAvailable': 'Video available',
    'admin.episodes.noVideo': 'No video',
    'admin.episodes.closePreview': 'Close Preview',
    'admin.episodes.editEpisode': 'Edit Episode',
    'admin.episodes.createEpisode': 'Create New Episode',
    'admin.episodes.titleEn': 'Title (English)',
    'admin.episodes.titleAr': 'Title (Arabic)',
    'admin.episodes.descEn': 'Description (English)',
    'admin.episodes.descAr': 'Description (Arabic)',
    'admin.episodes.duration': 'Duration (seconds)',
    'admin.episodes.order': 'Episode Order',
    'admin.episodes.accessType': 'Access Type',
    'admin.episodes.paid': 'Paid',
    'admin.episodes.videoUrl': 'Video URL',
    'admin.episodes.save': 'Save Episode',
    'admin.episodes.cancel': 'Cancel',
    'admin.episodes.min': 'min',

    // Admin Users
    'admin.users': 'Users & Enrollments',
    'admin.users.subtitle': 'Manage student accounts and course enrollments',
    'admin.users.registeredUsers': 'Registered Users',
    'admin.users.registeredStudents': 'Registered students',
    'admin.users.totalEnrollments': 'Total Enrollments',
    'admin.users.activeSubs': 'Active Subscriptions',
    'admin.users.name': 'Name',
    'admin.users.email': 'Email',
    'admin.users.phone': 'Phone',
    'admin.users.joined': 'Joined',
    'admin.users.active': 'Active',
    'admin.users.inactive': 'Inactive',
    'admin.users.free': 'Free',

    // Admin Keys
    'admin.keys.title': 'Registration Keys',
    'admin.keys.subtitle': 'Manage course access keys',
    'admin.keys.generateKey': 'Generate Key',
    'admin.keys.generateSingle': 'Generate Single Key',
    'admin.keys.bulkGenerate': 'Bulk Generate',
    'admin.keys.exportCsv': 'Export CSV',
    'admin.keys.totalKeys': 'Total Keys',
    'admin.keys.activated': 'Activated',
    'admin.keys.unused': 'Unused',
    'admin.keys.deactivated': 'Deactivated',
    'admin.keys.activationRate': 'Activation Rate',
    'admin.keys.searchKeys': 'Search Keys',
    'admin.keys.allKeys': 'All Keys',
    'admin.keys.keyCode': 'Key Code',
    'admin.keys.assignedTo': 'Assigned To',
    'admin.keys.course': 'Course',
    'admin.keys.statusLabel': 'Status',
    'admin.keys.activatedDate': 'Activated',
    'admin.keys.actions': 'Actions',
    'admin.keys.available': 'Available',
    'admin.keys.used': 'Used',
    'admin.keys.copy': 'Copy',
    'admin.keys.deactivate': 'Deactivate',
    'admin.keys.selectCourse': 'Select Course',
    'admin.keys.quantity': 'Quantity',
    'admin.keys.notes': 'Notes (optional)',
    'admin.keys.expiresAt': 'Expires At (optional)',
    'admin.keys.generate': 'Generate',
    'admin.keys.close': 'Close',
    'admin.keys.noKeys': 'No keys found',

    // Admin LexAI
    'admin.lexai.subscriptions': 'LexAI Subscriptions',
    'admin.lexai.subsSubtitle': 'Monitor active and expired LexAI plans',
    'admin.lexai.user': 'User',
    'admin.lexai.email': 'Email',
    'admin.lexai.status': 'Status',
    'admin.lexai.messages': 'Messages',
    'admin.lexai.ends': 'Ends',
    'admin.lexai.active': 'Active',
    'admin.lexai.expired': 'Expired',
    'admin.lexai.noSubs': 'No subscriptions found',
    'admin.lexai.keys': 'LexAI Keys',
    'admin.lexai.keysSubtitle': 'Generate manual keys for LexAI access',
    'admin.lexai.conversations': 'LexAI Conversations',
    'admin.lexai.convoSubtitle': 'Monitor and moderate user conversations',
    'admin.lexai.backToUsers': 'Back to Users',
    'admin.lexai.refresh': 'Refresh',
    'admin.lexai.deleteAll': 'Delete All Messages',
    'admin.lexai.deleteHistory': 'Delete Chat History',
    'admin.lexai.deleteConfirm': 'This will permanently delete all messages in this conversation. This action cannot be undone.',
    'admin.lexai.cancelDelete': 'Cancel',
    'admin.lexai.confirmDelete': 'Delete All',
    'admin.lexai.convoHistory': 'Conversation History',
    'admin.lexai.usersWithConvo': 'Users with Conversations',
    'admin.lexai.noConvos': 'No conversations yet',
    'admin.lexai.messagesCount': 'messages',
    'admin.lexai.lastMessage': 'Last message',
    'admin.lexai.selectConvo': 'Select a conversation to view messages',

    // Admin Recommendations
    'admin.rec.title': 'Recommendations Group Management',
    'admin.rec.subtitle': 'Manage analyst and recommendation keys',
    'admin.rec.totalKeys': 'Total Keys',
    'admin.rec.activated': 'Activated',
    'admin.rec.unused': 'Unused',
    'admin.rec.disabled': 'Disabled',
    'admin.rec.assignAnalyst': 'Assign Analyst',
    'admin.rec.searchUser': 'Search by name or email',
    'admin.rec.removeAnalyst': 'Remove analyst access',
    'admin.rec.setAnalyst': 'Set as analyst',
    'admin.rec.recKeys': 'Recommendation Keys',
    'admin.rec.generateSingle': 'Generate Single Key',
    'admin.rec.bulkGenerate': 'Bulk Generate',
    'admin.rec.keyCode': 'Key Code',
    'admin.rec.assignedTo': 'Assigned To',
    'admin.rec.status': 'Status',
    'admin.rec.activatedDate': 'Activated',
    'admin.rec.available': 'Available',
    'admin.rec.used': 'Used',
    'admin.rec.deactivated': 'Deactivated',
    'admin.rec.copy': 'Copy',
    'admin.rec.disable': 'Disable',
    'admin.rec.noKeys': 'No keys',
    'admin.rec.quantity': 'Quantity',

    // Admin Support Chat
    'admin.support.title': 'Support Chat',
    'admin.support.subtitle': 'View and respond to client support conversations',
    'admin.support.openConvos': 'Open Conversations',
    'admin.support.unread': 'Unread Messages',
    'admin.support.totalConvos': 'Total Conversations',
    'admin.support.convos': 'Conversations',
    'admin.support.open': 'Open',
    'admin.support.closed': 'Closed',
    'admin.support.close': 'Close',
    'admin.support.selectConvo': 'Select a conversation to view messages',
    'admin.support.replyPlaceholder': 'Type your reply...',
    'admin.support.send': 'Send',
    'admin.support.noConvos': 'No conversations yet',
    'admin.support.admin': 'Admin',
    'admin.support.support': 'Support',

    // Admin Roles
    'admin.roles.title': 'Role Management',
    'admin.roles.subtitle': 'Assign and manage user roles: Analyst, Support, Key Manager, and support permissions',
    'admin.roles.assignRole': 'Assign Role',
    'admin.roles.assignToUser': 'Assign Role to User',
    'admin.roles.selectUser': 'Select User',
    'admin.roles.selectRole': 'Select Role',
    'admin.roles.coreRoles': 'Core Roles',
    'admin.roles.supportPerms': 'Support Permissions',
    'admin.roles.allAssignments': 'All Role Assignments',
    'admin.roles.search': 'Search...',
    'admin.roles.noAssignments': 'No role assignments found',
    'admin.roles.user': 'User',
    'admin.roles.role': 'Role',
    'admin.roles.assignedAt': 'Assigned At',
    'admin.roles.assignedBy': 'Assigned By',
    'admin.roles.remove': 'Remove',
    'admin.roles.usersWithRole': 'users with this role',
    'admin.roles.analyst': 'Analyst',
    'admin.roles.support': 'Support',
    'admin.roles.keyManager': 'Key Manager',
    'admin.roles.viewProgress': 'View Progress',
    'admin.roles.viewRec': 'View Recommendations',
    'admin.roles.viewSubs': 'View Subscriptions',
    'admin.roles.viewQuizzes': 'View Quizzes',
    'admin.roles.clientLookup': 'Client Lookup',

    // Admin Quiz
    'admin.quiz.dashboard': 'Quiz Management Dashboard',
    'admin.quiz.dashSubtitle': 'Monitor quiz performance across all levels',
    'admin.quiz.userProgress': 'User Progress',
    'admin.quiz.manageQuestions': 'Manage Questions',
    'admin.quiz.analytics': 'Analytics',
    'admin.quiz.totalAttempts': 'Total Attempts',
    'admin.quiz.activeUsers': 'Active Users',
    'admin.quiz.avgScore': 'Average Score',
    'admin.quiz.passRate': 'Pass Rate',
    'admin.quiz.performByLevel': 'Performance by Level',
    'admin.quiz.level': 'Level',
    'admin.quiz.attempts': 'Attempts',
    'admin.quiz.passed': 'Passed',
    'admin.quiz.avgScoreLabel': 'Avg Score',
    'admin.quiz.passRateLabel': 'Pass Rate',
    'admin.quiz.difficultQs': 'Difficult Questions',
    'admin.quiz.question': 'Question',
    'admin.quiz.wrongAnswers': 'Wrong Answers',
    'admin.quiz.recentActivity': 'Recent Activity',
    'admin.quiz.user': 'User',
    'admin.quiz.score': 'Score',
    'admin.quiz.result': 'Result',
    'admin.quiz.date': 'Date',
    'admin.quiz.passedBadge': 'Passed',
    'admin.quiz.failedBadge': 'Failed',
    'admin.quiz.editQuestion': 'Edit Question',
    'admin.quiz.usersTitle': 'User Progress Monitoring',
    'admin.quiz.usersSubtitle': 'Track student quiz performance',
    'admin.quiz.backToDash': 'Back to Dashboard',
    'admin.quiz.searchUsers': 'Search by username or email...',
    'admin.quiz.totalUsers': 'Total Users',
    'admin.quiz.completedAll': 'Completed All Levels',
    'admin.quiz.allUsers': 'All Users',
    'admin.quiz.unlocked': 'Unlocked',
    'admin.quiz.bestScores': 'Best Scores',
    'admin.quiz.lastActivity': 'Last Activity',
    'admin.quiz.questionsTitle': 'Question Management',
    'admin.quiz.questionsSubtitle': 'Edit quiz questions and answers',
    'admin.quiz.editGuidelines': 'Editing Guidelines:',
    'admin.quiz.guideline1': 'Click on any question to edit it',
    'admin.quiz.guideline2': 'Mark the correct answer(s) using checkboxes',
    'admin.quiz.guideline3': 'Changes are saved immediately',
    'admin.quiz.questionText': 'Question Text',
    'admin.quiz.answerOptions': 'Answer Options (check correct answers)',
    'admin.quiz.saveChanges': 'Save Changes',
    'admin.quiz.cancelEdit': 'Cancel',
    'admin.quiz.questions': 'questions',

    // Analytics & Settings (placeholder pages)
    'admin.analytics.title': 'Analytics Dashboard',
    'admin.analytics.subtitle': 'View insights and metrics',
    'admin.analytics.comingSoon': 'Analytics Dashboard – Coming Soon',
    'admin.analytics.revenue': 'Track revenue and subscription trends',
    'admin.analytics.userGrowth': 'Monitor user growth and engagement',
    'admin.analytics.totalRevenue': 'Total Revenue',
    'admin.analytics.activeUsers': 'Active Users',
    'admin.analytics.courseCompletions': 'Course Completions',
    'admin.analytics.flexaiUsage': 'FlexAI Usage',

    'admin.settings.title': 'Settings',
    'admin.settings.subtitle': 'Manage your platform settings',
    'admin.settings.comingSoon': 'Settings Panel – Coming Soon',
    'admin.settings.notifications': 'Notifications',
    'admin.settings.notifDesc': 'Notification preferences',
    'admin.settings.security': 'Security',
    'admin.settings.secDesc': 'Security and authentication settings',
    'admin.settings.email': 'Email Settings',
    'admin.settings.emailDesc': 'Email configuration and templates',
    'admin.settings.database': 'Database',
    'admin.settings.dbDesc': 'Database management and backups',

    'admin.enrollments.title': 'Enrollments',
    'admin.enrollments.subtitle': 'Track student enrollments',
    'admin.enrollments.comingSoon': 'Enrollment Tracking – Coming Soon',
    'admin.enrollments.viewAll': 'View all student enrollments',
    'admin.enrollments.certificates': 'Generate completion certificates',
    'admin.enrollments.what': 'What are Enrollments?',
    'admin.enrollments.total': 'Total Enrollments',
    'admin.enrollments.activeStudents': 'Active Students',
    'admin.enrollments.completionRate': 'Completion Rate',

    // Common admin strings
    'admin.loading': 'Loading...',
    'admin.comingSoon': 'Coming Soon',
    'admin.unknown': 'Unknown',

    // Additional Dashboard keys
    'admin.dashboard.keysDesc': 'Generate and manage course registration keys',
    'admin.dashboard.coursesDesc': 'View and manage all courses and episodes',
    'admin.dashboard.usersDesc': 'Manage users and enrollments',
    'admin.totalEnrollments': 'Total Enrollments',

    // Additional Users page keys
    'admin.users.allUsersDesc': 'All users who have created accounts',
    'admin.users.courseEnrollments': 'Course Enrollments',
    'admin.users.enrollmentsDesc': 'All course enrollments and their status',
    'admin.users.lastSignIn': 'Last Sign In',
    'admin.users.user': 'User',
    'admin.users.course': 'Course',
    'admin.users.progress': 'Progress',
    'admin.users.payment': 'Payment',
    'admin.users.status': 'Status',
    'admin.users.enrolled': 'Enrolled',
    'admin.users.noUsers': 'No users yet',
    'admin.users.noEnrollments': 'No enrollments yet',
    'admin.users.currentlyActive': 'Currently active',
    'admin.users.enrollmentsSub': 'Course enrollments',
    'admin.users.allTimeRevenue': 'All-time revenue',

    // Additional Courses page keys
    'admin.courses.saving': 'Saving...',
    'admin.courses.update': 'Update',
    'admin.courses.create': 'Create',
    'admin.courses.deleteConfirm': 'Are you sure you want to delete this course? This will also delete all episodes and enrollments.',
    'admin.courses.noCoursesCta': 'Create your first course to get started!',
    'admin.courses.thumbnail.label': 'Course Thumbnail',

    // Additional Episodes page keys
    'admin.episodes.invalidCourse': 'Invalid course ID',
    'admin.episodes.createFirstDesc': 'Create your first episode to start building your course content',
    'admin.episodes.freePreview': 'Free Preview',
    'admin.episodes.premium': 'Premium',
    'admin.episodes.saving': 'Saving...',
    'admin.episodes.update': 'Update',
    'admin.episodes.create': 'Create',
    'admin.episodes.deleteConfirm': 'Are you sure you want to delete this episode?',
    'admin.episodes.fillBoth': 'Fill in the episode details in both English and Arabic',

    // Additional Keys page keys
    'admin.keys.manageCourseAccess': 'Manage course access keys for students',
    'admin.keys.createKeyDesc': 'Create a new registration key for a course',
    'admin.keys.bulkTitle': 'Generate Bulk Keys',
    'admin.keys.bulkDesc': 'Create multiple registration keys at once (max 1000)',
    'admin.keys.notActivated': 'Not activated',
    'admin.keys.created': 'Created',
    'admin.keys.generating': 'Generating...',
    'admin.keys.searchByEmail': 'Search by email...',
    'admin.keys.email': 'Email',

    // Additional LexAI keys
    'admin.lexai.generateKey': 'Generate Key',
    'admin.lexai.generateSingle': 'Generate Single Key',
    'admin.lexai.createKeyDesc': 'Create a new LexAI access key',
    'admin.lexai.bulkGenerate': 'Bulk Generate',
    'admin.lexai.bulkTitle': 'Generate Bulk Keys',
    'admin.lexai.bulkDesc': 'Create multiple LexAI keys at once (max 1000)',
    'admin.lexai.exportCsv': 'Export',
    'admin.lexai.notesLabel': 'Notes (Optional)',
    'admin.lexai.notesPlaceholder': 'Add notes about this key...',
    'admin.lexai.quantity': 'Quantity',
    'admin.lexai.generating': 'Generating...',
    'admin.lexai.generateKeys': 'Generate Keys',
    'admin.lexai.key': 'Key',
    'admin.lexai.created': 'Created',
    'admin.lexai.used': 'Used',
    'admin.lexai.notes': 'Notes',
    'admin.lexai.noKeys': 'No keys found',
    'admin.lexai.available': 'Available',
    'admin.lexai.deactivated': 'Deactivated',
    'admin.lexai.activated': 'Activated',
    'admin.lexai.totalKeys': 'Total Keys',
    'admin.lexai.unusedKeys': 'Unused',
    'admin.lexai.deactivatedKeys': 'Deactivated',
    'admin.lexai.clickToView': 'Click on a user to view their chat history',
    'admin.lexai.loadingMessages': 'Loading messages...',
    'admin.lexai.noMessages': 'No messages found',

    // Additional Roles keys
    'admin.roles.email': 'Email',
    'admin.roles.actions': 'Actions',
    'admin.roles.assigning': 'Assigning...',
    'admin.roles.userLabel': 'users with this role',

    // Additional Quiz keys
    'admin.quiz.loadingStats': 'Loading statistics...',
    'admin.quiz.loadingUsers': 'Loading users...',
    'admin.quiz.loadingQuestions': 'Loading questions...',
    'admin.quiz.failedToLoad': 'Failed to load data',
    'admin.quiz.viewStudents': 'View all students',
    'admin.quiz.editContent': 'Edit quiz content',
    'admin.quiz.detailedReports': 'Detailed reports',
    'admin.quiz.title': 'Title',
    'admin.quiz.completion': 'Completion',
    'admin.quiz.lowestCorrectRate': 'Questions with lowest correct rate',
    'admin.quiz.correctPct': 'correct',
    'admin.quiz.latestAttempts': 'Latest quiz attempts',
    'admin.quiz.noData': 'No data yet',
    'admin.quiz.noActivity': 'No activity yet',
    'admin.quiz.noUsersFound': 'No users found matching your search',
    'admin.quiz.noUsers': 'No users yet',
    'admin.quiz.completed': 'Completed',
    'admin.quiz.resetProgress': 'Reset Progress',
    'admin.quiz.viewDetails': 'View Details',
    'admin.quiz.saving': 'Saving...',
    'admin.quiz.correctRate': 'correct rate',
    'admin.quiz.attempted': 'Attempted',
    'admin.quiz.times': 'times',

    // Additional Analytics keys
    'admin.analytics.building': "We're building powerful analytics features for you",
    'admin.analytics.underDev': "The analytics dashboard is currently under development. Soon you'll be able to:",
    'admin.analytics.viewCompletionRates': 'View course completion rates',
    'admin.analytics.analyzeUsage': 'Analyze FlexAI usage statistics',
    'admin.analytics.revenueTracking': 'Revenue tracking',
    'admin.analytics.userAnalytics': 'User analytics',
    'admin.analytics.courseMetrics': 'Course metrics',
    'admin.analytics.aiAnalytics': 'AI analytics',

    // Additional Settings keys
    'admin.settings.advancedDev': 'Advanced configuration options are being developed',
    'admin.settings.underDev': 'The settings panel is currently under development. Soon you will be able to configure:',
    'admin.settings.notifPref': 'Notification preferences',
    'admin.settings.secSettings': 'Security and authentication settings',
    'admin.settings.emailTemplates': 'Email templates and notifications',
    'admin.settings.dbBackup': 'Database backup and maintenance',
    'admin.settings.configNotif': 'Configure notification preferences',
    'admin.settings.manageSecurity': 'Manage security settings',
    'admin.settings.configEmail': 'Configure email templates',
    'admin.settings.dbMaintenance': 'Database maintenance options',

    // Additional Enrollments keys
    'admin.enrollments.trackDesc': 'Track student enrollments and course progress',
    'admin.enrollments.devDesc': 'Student progress tracking features are being developed',
    'admin.enrollments.underDev': 'The enrollment tracking system is currently under development. Soon you will be able to:',
    'admin.enrollments.trackProgress': 'Track course progress and completion',
    'admin.enrollments.monitorEngagement': 'Monitor student engagement metrics',
    'admin.enrollments.whatDesc': 'Understanding the enrollment system',
    'admin.enrollments.whatText': 'Enrollments track which students are taking which courses and their progress through the material.',
    'admin.enrollments.keyFeatures': 'Key Features (When Implemented):',
    'admin.enrollments.feature1': 'Track which users have access to which courses',
    'admin.enrollments.feature2': 'Monitor video watch progress',
    'admin.enrollments.feature3': 'See completion rates per course',
    'admin.enrollments.feature4': 'Identify struggling students who need help',
    'admin.enrollments.feature5': 'Generate reports on student performance',
    'admin.enrollments.note': 'Currently, course access is managed through registration keys. The enrollment tracking system will provide deeper insights into student progress.',
    'admin.enrollments.studentEnrollments': 'Student enrollments',
    'admin.enrollments.currentlyLearning': 'Currently learning',
    'admin.enrollments.averageCompletion': 'Average completion',

    // Auth Pages
    'auth.login.title': 'Welcome Back',
    'auth.login.description': 'Sign in to continue learning',
    'auth.login.adminTitle': 'Admin Login',
    'auth.login.adminDescription': 'Sign in to access the admin panel',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.emailPlaceholder': 'john@example.com',
    'auth.login.passwordPlaceholder': '••••••••',
    'auth.login.submit': 'Sign In',
    'auth.login.submitting': 'Signing In...',
    'auth.login.allFieldsRequired': 'All fields are required',
    
    'auth.register.title': 'Create Account',
    'auth.register.description': 'Sign up to start learning trading',
    'auth.register.fullName': 'Full Name',
    'auth.register.email': 'Email',
    'auth.register.password': 'Password',
    'auth.register.confirmPassword': 'Confirm Password',
    'auth.register.namePlaceholder': 'John Doe',
    'auth.register.emailPlaceholder': 'john@example.com',
    'auth.register.passwordPlaceholder': '••••••••',
    'auth.register.passwordHint': 'At least 8 characters with 1 uppercase, 1 lowercase, and 1 number',
    'auth.register.submit': 'Create Account',
    'auth.register.submitting': 'Creating Account...',
    'auth.register.allFieldsRequired': 'All fields are required',
    'auth.register.passwordMismatch': 'Passwords do not match',
    'auth.register.passwordTooShort': 'Password must be at least 8 characters',
    
    'auth.page.backToHome': '← Back to Home',
    'auth.page.tagline': 'Master the art of trading',
    'auth.page.switchToRegister': "Don't have an account?",
    'auth.page.switchToLogin': 'Already have an account?',
    'auth.page.signUp': 'Sign up',
    'auth.page.signIn': 'Sign in',
    
    // Profile Page
    'profile.title': 'Account Settings',
    'profile.description': 'Manage your profile and security settings',
    'profile.backToDashboard': 'Back to Dashboard',
    'profile.email': 'Email',
    'profile.emailReadonly': 'Email cannot be changed',
    'profile.name': 'Full Name',
    'profile.nameplaceholder': 'Enter your full name',
    'profile.phone': 'Phone Number',
    'profile.phoneExample': '+1 (555) 000-0000',
    'profile.saveChanges': 'Save Changes',
    'profile.updating': 'Saving...',
    'profile.cancel': 'Cancel',
    'profile.updates.success': 'Profile updated successfully',
    'profile.error': 'Error',
    
    'profile.profileInfo.title': 'Profile Information',
    'profile.profileInfo.description': 'Update your personal information',
    
    'profile.security.title': 'Security',
    'profile.security.description': 'Manage your password and security settings',
    'profile.password.change': 'Change Password',
    'profile.password.current': 'Current Password',
    'profile.password.new': 'New Password',
    'profile.password.confirm': 'Confirm New Password',
    'profile.password.enterCurrent': 'Enter your current password',
    'profile.password.enterNew': 'Enter your new password',
    'profile.password.confirmNew': 'Confirm your new password',
    'profile.password.requirements': 'Minimum 8 characters with uppercase, lowercase, and numbers',
    'profile.password.allFieldsRequired': 'All password fields are required',
    'profile.password.mismatch': 'New passwords do not match',
    'profile.password.tooShort': 'Password must be at least 8 characters',
    'profile.password.changed': 'Password changed successfully',
    'profile.password.update': 'Update Password',
    'profile.password.updating': 'Updating password...',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.back': 'Back',

    // Support Chat
    'support.title': 'Support Chat',
    'support.subtitle': 'We\'re here to help',
    'support.empty': 'No messages yet',
    'support.emptyHint': 'Send a message to start a conversation with our support team',
    'support.placeholder': 'Type your message...',
    'support.agent': 'Support',
    'support.admin': 'Admin',

    // Recommendations Page
    'rec.title': 'Recommendations Group',
    'rec.subtitle': 'Live alerts and recommendations with quick copy for execution',
    'rec.accessStatus': 'Access Status',
    'rec.accessDesc': 'Recommendations group subscription is separate from the course and LexAI',
    'rec.checking': 'Checking...',
    'rec.status': 'Status',
    'rec.activated': 'Active',
    'rec.notActivated': 'Not active',
    'rec.expiryDate': 'Expiry date',
    'rec.enterKey': 'Enter recommendations key',
    'rec.activateKey': 'Activate Key',
    'rec.publishNew': 'Publish New Recommendation',
    'rec.publishDesc': 'For the analyst/staff managing the group',
    'rec.typeAlert': 'Alert',
    'rec.typeRecommendation': 'Recommendation',
    'rec.typeResult': 'Result',
    'rec.symbolPlaceholder': 'Pair/Asset (optional)',
    'rec.sidePlaceholder': 'Direction BUY/SELL (optional)',
    'rec.entryPlaceholder': 'Entry price (optional)',
    'rec.slPlaceholder': 'Stop loss (optional)',
    'rec.tp1Placeholder': 'Target 1 (optional)',
    'rec.tp2Placeholder': 'Target 2 (optional)',
    'rec.riskPlaceholder': 'Risk percentage (optional)',
    'rec.messagePlaceholder': 'Write the recommendation or result here...',
    'rec.publishBtn': 'Publish + Send Email',
    'rec.messages': 'Messages',
    'rec.messagesDesc': 'Live group updates',
    'rec.loadingMessages': 'Loading messages...',
    'rec.noMessages': 'No messages yet.',
    'rec.analyst': 'Analyst',
    'rec.copy': 'Copy',
    'rec.toastKeyActivated': 'Recommendations group key activated successfully',
    'rec.toastPublished': 'Message published and notifications sent',
    'rec.toastEnterKey': 'Please enter the key',
    'rec.toastWriteMessage': 'Please write a message',
    'rec.toastCopied': 'Recommendation copied',
    'rec.copySymbol': 'Pair/Asset',
    'rec.copySide': 'Direction',
    'rec.copyEntry': 'Entry',
    'rec.copySL': 'Stop Loss',
    'rec.copyTP1': 'Target 1',
    'rec.copyTP2': 'Target 2',
    'rec.copyRisk': 'Risk Percentage',

    // CourseWatch Page
    'course.loading': 'Loading course...',
    'course.notFound': 'Course not found',
    'course.backHome': 'Back to Home',
    'course.signInRequired': 'Sign in required',
    'course.signInToAccess': 'Please sign in to access this course',
    'course.signInBtn': 'Sign In to Continue',
    'course.enrollRequired': 'Enrollment required',
    'course.enrollDesc': 'You need to enroll in this course to access the content',
    'course.oneTimePayment': 'One-time payment',
    'course.enrollNow': 'Enroll Now',
    'course.progress': 'Progress',
    'course.episode': 'Episode',
    'course.free': 'FREE',
    'course.markComplete': 'Mark as Complete',
    'course.nextEpisode': 'Next Episode',
    'course.watchProgress': 'Watch progress',
    'course.required': 'required',
    'course.episodeQuiz': 'Episode Quiz',
    'course.quizDesc': 'Pass at least 50% to unlock completion for this episode.',
    'course.loadingQuiz': 'Loading quiz...',
    'course.noQuiz': 'Quiz is not configured for this episode yet.',
    'course.quizPassed': 'Quiz passed. You can now mark this episode as complete.',
    'course.submitQuiz': 'Submit Quiz',
    'course.score': 'Score',
    'course.requiredScore': 'Required',
    'course.aboutCourse': 'About this course',
    'course.level': 'Level',
    'course.episodes': 'Episodes',
    'course.courseProgress': 'Course Progress',
    'course.ofEpisodes': 'of',
    'course.episodesCompleted': 'episodes completed',
    'course.percentComplete': 'complete',
    'course.min': 'min',
    'course.toastCompleted': 'Episode marked as complete!',
    'course.toastCompleteFail': 'Unable to mark episode complete',
    'course.toastAnswerAll': 'Please answer all questions',
    'course.toastUnlockPrev': 'Complete previous episodes to unlock this one.',
  },
  ar: {
    // Header/Navigation
    'nav.myCourses': 'دوراتي',
    'nav.lexai': 'ليكس إيه آي',
    'nav.adminPanel': 'لوحة الإدارة',
    'nav.logout': 'تسجيل الخروج',
    'nav.login': 'تسجيل الدخول',
    
    // Homepage
    'home.hero.title': 'أتقن التداول مع',
    'home.hero.subtitle': 'إرشاد الخبراء',
    'home.hero.description': 'تعلم من خبراء الصناعة وارتقِ بمهاراتك في التداول إلى المستوى التالي من خلال دوراتنا الشاملة. ابدأ رحلتك نحو الحرية المالية اليوم.',
    'home.hero.browseCourses': 'تصفح الدورات',
    'home.hero.startTrial': 'ابدأ تجربة مجانية',
    'home.hero.activeStudents': 'طالب نشط',
    'home.hero.expertCourses': 'دورة احترافية',
    'home.hero.rating': 'التقييم',
    
    'home.cta.title': 'ابدأ اليوم',
    'home.cta.subtitle': 'انضم إلى آلاف المتداولين الناجحين',
    'home.cta.email': 'أدخل بريدك الإلكتروني',
    'home.cta.password': 'اختر كلمة مرور',
    'home.cta.createAccount': 'إنشاء حساب مجاني',
    'home.cta.haveAccount': 'هل لديك حساب بالفعل؟',
    'home.cta.signIn': 'تسجيل الدخول',
    'home.cta.guarantee': 'ضمان استرداد الأموال لمدة 30 يومًا',
    
    'home.why.title': 'لماذا تختار أكاديمية XFlex؟',
    'home.why.subtitle': 'كل ما تحتاجه لتصبح متداولًا ناجحًا في مكان واحد',
    'home.why.expertCourses': 'دورات يقودها خبراء',
    'home.why.expertDesc': 'تعلم من متداولين ذوي خبرة وسجلات حافلة في الأسواق',
    'home.why.practicalStrategies': 'استراتيجيات عملية',
    'home.why.practicalDesc': 'طبق استراتيجيات تداول حقيقية تعمل في أسواق اليوم',
    'home.why.lifetimeAccess': 'وصول مدى الحياة',
    'home.why.lifetimeDesc': 'احصل على وصول غير محدود إلى مواد الدورة والتحديثات المستقبلية',
    
    'home.courses.title': 'الدورات المتاحة',
    'home.courses.subtitle': 'اختر من مجموعتنا من دورات التداول المصممة لجميع مستويات المهارة',
    'home.courses.noCourses': 'لا توجد دورات متاحة حتى الآن. تحقق مرة أخرى قريبًا!',
    
    // Services Section
    'home.services.title': 'خدماتنا',
    'home.services.subtitle': 'كل ما تحتاجه للنجاح في تداول الفوركس',
    
    // Course Card
    'home.service.course.title': 'دورات التداول',
    'home.service.course.desc': 'تعلم تداول الفوركس من الأساسيات إلى الاستراتيجيات المتقدمة عبر دورات فيديو شاملة.',
    'home.service.course.f1': 'دورة تداول كاملة',
    'home.service.course.f2': 'استراتيجيات حركة السعر',
    'home.service.course.f3': 'إدارة المخاطر',
    'home.service.course.f4': 'التحليل الفني',
    'home.service.course.cta': 'تفعيل الوصول للدورة',
    'home.service.course.price': 'دفعة واحدة',
    
    // Recommendations Card
    'home.service.rec.title': 'قروب التوصيات',
    'home.service.rec.desc': 'توصيات تداول حية من محللين خبراء مع تنبيهات فورية وإشعارات بالبريد الإلكتروني.',
    'home.service.rec.f1': 'توصيات تداول حية',
    'home.service.rec.f2': 'منشورات محللين خبراء',
    'home.service.rec.f3': 'تنبيهات بريد إلكتروني فورية',
    'home.service.rec.f4': 'تفاعلات مباشرة',
    'home.service.rec.cta': 'اشترك الآن',
    'home.service.rec.price': '$100 / شهرياً',
    
    // LexAI Card
    'home.service.lexai.title': 'مساعد LexAI',
    'home.service.lexai.desc': 'احصل على تحليل الرسوم البيانية وتوصيات التداول بالذكاء الاصطناعي المتقدم.',
    'home.service.lexai.f1': 'تحليل متعدد الأطر الزمنية',
    'home.service.lexai.f2': 'مستويات الدعم والمقاومة',
    'home.service.lexai.f3': 'نقاط الدخول والخروج',
    'home.service.lexai.f4': 'نصائح إدارة المخاطر',
    'home.service.lexai.cta': 'تفعيل LexAI (30 يوم)',
    'home.service.lexai.price': '$30 / شهرياً',
    
    // Already Registered
    'home.alreadyRegistered': 'مسجل مسبقاً؟',
    'home.loginHere': 'سجل الدخول هنا',
    
    // Contact Support
    'home.contact.title': 'تواصل مع الدعم',
    'home.contact.subtitle': 'هل لديك سؤال؟ أرسل لنا رسالة وسنعود إليك قريباً.',
    'home.contact.email': 'بريدك الإلكتروني',
    'home.contact.emailPlaceholder': 'email@example.com',
    'home.contact.message': 'رسالتك',
    'home.contact.messagePlaceholder': 'كيف يمكننا مساعدتك؟',
    'home.contact.send': 'إرسال الرسالة',
    'home.contact.sending': 'جاري الإرسال...',
    'home.contact.sent': 'تم إرسال الرسالة! سنعود إليك قريباً.',
    
    'home.footer.tagline': 'تمكين المتداولين في جميع أنحاء العالم بالمعرفة والمهارات العملية',
    'home.footer.rights': 'جميع الحقوق محفوظة.',
    
    // Dashboard
    'dashboard.title': 'مرحبًا بك مجددًا، {name}!',
    'dashboard.subtitle': 'تابع رحلتك التعليمية',
    'dashboard.settings': 'الإعدادات',
    'dashboard.logout': 'تسجيل الخروج',
    'dashboard.loading': 'جاري تحميل لوحتك...',
    'dashboard.signInTitle': 'مرحبًا بك في أكاديمية XFlex',
    'dashboard.signInDesc': 'سجل الدخول للوصول إلى لوحة التعلم',
    'dashboard.signInBtn': 'تسجيل الدخول للمتابعة',
    'dashboard.stats.totalCourses': 'إجمالي الدورات',
    'dashboard.stats.enrolledLabel': 'دورات مسجلة',
    'dashboard.stats.enrolledCourses': 'الدورات المسجلة',
    'dashboard.stats.courses': 'دورات نشطة',
    'dashboard.stats.completedCourses': 'مكتملة',
    'dashboard.stats.finished': 'دورات منتهية',
    'dashboard.stats.inProgress': 'قيد التقدم',
    'dashboard.stats.activeLearning': 'تعلم نشط',
    'dashboard.stats.avgProgress': 'متوسط التقدم',
    'dashboard.stats.overallCompletion': 'الإكمال العام',
    'dashboard.stats.quizzesPassed': 'الاختبارات المجتازة',
    'dashboard.stats.levels': 'مستويات الاختبار المكتملة',
    'dashboard.enrolledCourses.title': 'دوراتي',
    'dashboard.enrolledCourses.description': 'تابع التعلم وراقب تقدمك',
    'dashboard.noCoursesEnrolled': 'لم تسجل في أي دورات بعد',
    'dashboard.noCoursesTitle': 'لا توجد دورات بعد',
    'dashboard.noCoursesDesc': 'ابدأ التعلم بالتسجيل في دورة',
    'dashboard.browseCourses': 'تصفح الدورات',
    'dashboard.completed': 'مكتمل',
    'dashboard.episodes': 'حلقات',
    'dashboard.episodesCompleted': 'حلقات مكتملة',
    'dashboard.progress': 'التقدم',
    'dashboard.continue': 'متابعة التعلم',
    'dashboard.review': 'مراجعة الدورة',
    'dashboard.myAccess': 'وصولي',
    'dashboard.myAccessDesc': 'حالة اشتراكاتك مرتبطة ببريدك الإلكتروني.',
    'dashboard.courseAccess': 'الدورة',
    'dashboard.lexaiAccess': 'LexAI',
    'dashboard.recAccess': 'التوصيات',
    'dashboard.active': 'مفعل',
    'dashboard.notActive': 'غير مفعل',
    'dashboard.openCourses': 'فتح الدورات',
    'dashboard.openLexai': 'فتح LexAI',
    'dashboard.openRec': 'فتح التوصيات',
    'dashboard.activateRec': 'تفعيل التوصيات',
    'dashboard.nav.home': 'الرئيسية',
    'dashboard.nav.dashboard': 'لوحتي',
    'dashboard.nav.quizzes': 'الاختبارات',
    'dashboard.nav.lexai': 'LexAI',
    'dashboard.nav.rec': 'قروب التوصيات',
    'dashboard.nav.support': 'الدعم',
    'dashboard.quickActions.browseMore': 'استكشف المزيد',
    'dashboard.quickActions.discoverNewCourses': 'استكشف المزيد من دورات التداول وكسّع معلوماتك',
    'dashboard.quickActions.browseCourses': 'استعرض جميع الدورات',
    'dashboard.quickActions.aiAssistant': 'مساعد FlexAI',
    'dashboard.quickActions.getAIHelp': 'احصل على مساعدة فورية من مساعد الذكاء الاصطناعي للتداول',
    'dashboard.quickActions.openChat': 'فتح الدردشة',
    
    // LexAI
    'lexai.title': 'ليكس إيه آي - تحليل العملات بالذكاء الاصطناعي',
    'lexai.subscribe.title': 'اشترك في ليكس إيه آي',
    'lexai.subscribe.desc': 'احصل على تحليل العملات وتوصيات التداول بالذكاء الاصطناعي',
    'lexai.subscribe.price': '$29.99/شهريًا',
    'lexai.subscribe.feature1': '100 تحليل رسم بياني شهريًا',
    'lexai.subscribe.feature2': 'رؤى السوق في الوقت الفعلي',
    'lexai.subscribe.feature3': 'توصيات التداول',
    'lexai.subscribe.feature4': 'تقارير التحليل الفني',
    'lexai.subscribe.button': 'اشترك الآن',
    'lexai.chat.title': 'الدردشة مع ليكس إيه آي',
    'lexai.chat.remaining': 'تحليل متبقي هذا الشهر',
    'lexai.chat.placeholder': 'اسأل عن تحليل العملات أو قم بتحميل صورة الرسم البياني...',
    'lexai.chat.send': 'إرسال',
    'lexai.chat.uploadImage': 'تحميل صورة الرسم البياني',
    'lexai.chat.uploading': 'جاري التحميل...',
    
    // Admin Sidebar
    'admin.sidebar.overview': 'نظرة عامة',
    'admin.sidebar.dashboard': 'لوحة التحكم',
    'admin.sidebar.content': 'المحتوى',
    'admin.sidebar.courses': 'الدورات',
    'admin.sidebar.courseKeys': 'مفاتيح الدورات',
    'admin.sidebar.quizzes': 'الاختبارات',
    'admin.sidebar.quizDashboard': 'لوحة التحكم',
    'admin.sidebar.quizUsers': 'تقدم الطلاب',
    'admin.sidebar.quizQuestions': 'الأسئلة',
    'admin.sidebar.lexai': 'ليكس إيه آي',
    'admin.sidebar.conversations': 'المحادثات',
    'admin.sidebar.subscriptions': 'الاشتراكات',
    'admin.sidebar.lexaiKeys': 'مفاتيح LexAI',
    'admin.sidebar.users': 'المستخدمون',
    'admin.sidebar.usersList': 'جميع المستخدمين',
    'admin.sidebar.enrollments': 'التسجيلات',
    'admin.sidebar.recommendations': 'التوصيات',
    'admin.sidebar.groupMgmt': 'إدارة القروب',
    'admin.sidebar.support': 'الدعم والموظفون',
    'admin.sidebar.supportChat': 'الدعم الفني',
    'admin.sidebar.supportDash': 'لوحة الدعم',
    'admin.sidebar.staffPortal': 'بوابة الموظفين',
    'admin.sidebar.roles': 'الأدوار',
    'admin.sidebar.analytics': 'التحليلات',
    'admin.sidebar.settings': 'الإعدادات',
    'admin.sidebar.signOut': 'تسجيل الخروج',

    // Admin Dashboard
    'admin.dashboard': 'لوحة التحكم',
    'admin.dashboard.welcome': 'مرحبًا بك في لوحة الإدارة',
    'admin.dashboard.subtitle': 'إدارة المنصة من هنا',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalCourses': 'إجمالي الدورات',
    'admin.activeEnrollments': 'التسجيلات النشطة',
    'admin.totalRevenue': 'إجمالي الإيرادات',
    'admin.dashboard.registeredStudents': 'الطلاب المسجلين',
    'admin.dashboard.publishedCourses': 'الدورات المنشورة',
    'admin.dashboard.activeSubs': 'الاشتراكات النشطة',
    'admin.dashboard.keys': 'مفاتيح تسجيل الدورات',
    'admin.dashboard.manageKeys': 'إدارة المفاتيح',
    'admin.dashboard.courses': 'الدورات',
    'admin.dashboard.viewCourses': 'عرض الدورات',
    'admin.dashboard.users': 'المستخدمون',
    'admin.dashboard.viewUsers': 'عرض المستخدمين',
    'admin.dashboard.recentEnrollments': 'التسجيلات الأخيرة',
    'admin.dashboard.noEnrollments': 'لا توجد تسجيلات بعد',
    'admin.dashboard.enrolled': 'مسجل',
    'admin.dashboard.quickActions': 'إجراءات سريعة',

    // Admin Courses
    'admin.courses': 'الدورات',
    'admin.courses.subtitle': 'إدارة دورات التداول',
    'admin.courses.addCourse': 'إضافة دورة',
    'admin.courses.noCourses': 'لا توجد دورات بعد.',
    'admin.courses.manageEpisodes': 'إدارة الحلقات',
    'admin.courses.edit': 'تعديل',
    'admin.courses.editCourse': 'تعديل الدورة',
    'admin.courses.createCourse': 'إنشاء دورة جديدة',
    'admin.courses.fillBoth': 'أدخل بيانات الدورة بالإنجليزية والعربية',
    'admin.courses.titleEn': 'العنوان (إنجليزي)',
    'admin.courses.titleAr': 'العنوان (عربي)',
    'admin.courses.descEn': 'الوصف (إنجليزي)',
    'admin.courses.descAr': 'الوصف (عربي)',
    'admin.courses.price': 'السعر (دولار)',
    'admin.courses.level': 'المستوى',
    'admin.courses.status': 'الحالة',
    'admin.courses.thumbnail': 'رابط الصورة',
    'admin.courses.beginner': 'مبتدئ',
    'admin.courses.intermediate': 'متوسط',
    'admin.courses.advanced': 'متقدم',
    'admin.courses.draft': 'مسودة',
    'admin.courses.published': 'منشور',
    'admin.courses.save': 'حفظ الدورة',
    'admin.courses.cancel': 'إلغاء',
    'admin.courses.episodes': 'حلقات',

    // Admin Episodes
    'admin.episodes': 'الحلقات',
    'admin.episodes.backToCourses': 'العودة للدورات',
    'admin.episodes.subtitle': 'إدارة حلقات الدورة',
    'admin.episodes.addEpisode': 'إضافة حلقة',
    'admin.episodes.noEpisodes': 'لا توجد حلقات بعد',
    'admin.episodes.createFirst': 'إنشاء أول حلقة',
    'admin.episodes.free': 'مجاني',
    'admin.episodes.videoAvailable': 'فيديو متاح',
    'admin.episodes.noVideo': 'لا يوجد فيديو',
    'admin.episodes.closePreview': 'إغلاق المعاينة',
    'admin.episodes.editEpisode': 'تعديل الحلقة',
    'admin.episodes.createEpisode': 'إنشاء حلقة جديدة',
    'admin.episodes.titleEn': 'العنوان (إنجليزي)',
    'admin.episodes.titleAr': 'العنوان (عربي)',
    'admin.episodes.descEn': 'الوصف (إنجليزي)',
    'admin.episodes.descAr': 'الوصف (عربي)',
    'admin.episodes.duration': 'المدة (ثواني)',
    'admin.episodes.order': 'ترتيب الحلقة',
    'admin.episodes.accessType': 'نوع الوصول',
    'admin.episodes.paid': 'مدفوع',
    'admin.episodes.videoUrl': 'رابط الفيديو',
    'admin.episodes.save': 'حفظ الحلقة',
    'admin.episodes.cancel': 'إلغاء',
    'admin.episodes.min': 'دقيقة',

    // Admin Users
    'admin.users': 'المستخدمون والتسجيلات',
    'admin.users.subtitle': 'إدارة حسابات الطلاب وتسجيلاتهم',
    'admin.users.registeredUsers': 'المستخدمون المسجلون',
    'admin.users.registeredStudents': 'الطلاب المسجلين',
    'admin.users.totalEnrollments': 'إجمالي التسجيلات',
    'admin.users.activeSubs': 'الاشتراكات النشطة',
    'admin.users.name': 'الاسم',
    'admin.users.email': 'الإيميل',
    'admin.users.phone': 'الهاتف',
    'admin.users.joined': 'الانضمام',
    'admin.users.active': 'نشط',
    'admin.users.inactive': 'غير نشط',
    'admin.users.free': 'مجاني',

    // Admin Keys
    'admin.keys.title': 'مفاتيح التسجيل',
    'admin.keys.subtitle': 'إدارة مفاتيح الوصول للدورات',
    'admin.keys.generateKey': 'إنشاء مفتاح',
    'admin.keys.generateSingle': 'إنشاء مفتاح واحد',
    'admin.keys.bulkGenerate': 'إنشاء دفعة',
    'admin.keys.exportCsv': 'تصدير CSV',
    'admin.keys.totalKeys': 'إجمالي المفاتيح',
    'admin.keys.activated': 'مفعلة',
    'admin.keys.unused': 'غير مستخدمة',
    'admin.keys.deactivated': 'معطلة',
    'admin.keys.activationRate': 'نسبة التفعيل',
    'admin.keys.searchKeys': 'بحث في المفاتيح',
    'admin.keys.allKeys': 'جميع المفاتيح',
    'admin.keys.keyCode': 'رمز المفتاح',
    'admin.keys.assignedTo': 'مُعيّن لـ',
    'admin.keys.course': 'الدورة',
    'admin.keys.statusLabel': 'الحالة',
    'admin.keys.activatedDate': 'تاريخ التفعيل',
    'admin.keys.actions': 'إجراءات',
    'admin.keys.available': 'متاح',
    'admin.keys.used': 'مستخدم',
    'admin.keys.copy': 'نسخ',
    'admin.keys.deactivate': 'تعطيل',
    'admin.keys.selectCourse': 'اختر الدورة',
    'admin.keys.quantity': 'الكمية',
    'admin.keys.notes': 'ملاحظات (اختياري)',
    'admin.keys.expiresAt': 'تاريخ الانتهاء (اختياري)',
    'admin.keys.generate': 'إنشاء',
    'admin.keys.close': 'إغلاق',
    'admin.keys.noKeys': 'لا توجد مفاتيح',

    // Admin LexAI
    'admin.lexai.subscriptions': 'اشتراكات LexAI',
    'admin.lexai.subsSubtitle': 'مراقبة الاشتراكات النشطة والمنتهية',
    'admin.lexai.user': 'المستخدم',
    'admin.lexai.email': 'الإيميل',
    'admin.lexai.status': 'الحالة',
    'admin.lexai.messages': 'الرسائل',
    'admin.lexai.ends': 'ينتهي',
    'admin.lexai.active': 'نشط',
    'admin.lexai.expired': 'منتهي',
    'admin.lexai.noSubs': 'لا توجد اشتراكات',
    'admin.lexai.keys': 'مفاتيح LexAI',
    'admin.lexai.keysSubtitle': 'إنشاء مفاتيح LexAI يدويًا',
    'admin.lexai.conversations': 'محادثات LexAI',
    'admin.lexai.convoSubtitle': 'مراقبة وإدارة محادثات المستخدمين',
    'admin.lexai.backToUsers': 'العودة للمستخدمين',
    'admin.lexai.refresh': 'تحديث',
    'admin.lexai.deleteAll': 'حذف جميع الرسائل',
    'admin.lexai.deleteHistory': 'حذف سجل المحادثة',
    'admin.lexai.deleteConfirm': 'سيتم حذف جميع الرسائل نهائيًا. لا يمكن التراجع عن هذا الإجراء.',
    'admin.lexai.cancelDelete': 'إلغاء',
    'admin.lexai.confirmDelete': 'حذف الكل',
    'admin.lexai.convoHistory': 'سجل المحادثة',
    'admin.lexai.usersWithConvo': 'المستخدمون مع محادثات',
    'admin.lexai.noConvos': 'لا توجد محادثات بعد',
    'admin.lexai.messagesCount': 'رسالة',
    'admin.lexai.lastMessage': 'آخر رسالة',
    'admin.lexai.selectConvo': 'اختر محادثة لعرض الرسائل',

    // Admin Recommendations
    'admin.rec.title': 'إدارة قروب التوصيات',
    'admin.rec.subtitle': 'إدارة المحللين ومفاتيح التوصيات',
    'admin.rec.totalKeys': 'إجمالي المفاتيح',
    'admin.rec.activated': 'مفعلة',
    'admin.rec.unused': 'غير مستخدمة',
    'admin.rec.disabled': 'معطلة',
    'admin.rec.assignAnalyst': 'تعيين المحلل',
    'admin.rec.searchUser': 'بحث بالاسم أو البريد',
    'admin.rec.removeAnalyst': 'إزالة صلاحية المحلل',
    'admin.rec.setAnalyst': 'تعيين كمحلل',
    'admin.rec.recKeys': 'مفاتيح التوصيات',
    'admin.rec.generateSingle': 'إنشاء مفتاح واحد',
    'admin.rec.bulkGenerate': 'إنشاء دفعة',
    'admin.rec.keyCode': 'رمز المفتاح',
    'admin.rec.assignedTo': 'مُعيّن لـ',
    'admin.rec.status': 'الحالة',
    'admin.rec.activatedDate': 'تاريخ التفعيل',
    'admin.rec.available': 'متاح',
    'admin.rec.used': 'مستخدم',
    'admin.rec.deactivated': 'معطل',
    'admin.rec.copy': 'نسخ',
    'admin.rec.disable': 'تعطيل',
    'admin.rec.noKeys': 'لا توجد مفاتيح',
    'admin.rec.quantity': 'الكمية',

    // Admin Support Chat
    'admin.support.title': 'الدعم الفني',
    'admin.support.subtitle': 'عرض والرد على محادثات الدعم',
    'admin.support.openConvos': 'محادثات مفتوحة',
    'admin.support.unread': 'رسائل غير مقروءة',
    'admin.support.totalConvos': 'إجمالي المحادثات',
    'admin.support.convos': 'المحادثات',
    'admin.support.open': 'مفتوح',
    'admin.support.closed': 'مغلق',
    'admin.support.close': 'إغلاق',
    'admin.support.selectConvo': 'اختر محادثة لعرض الرسائل',
    'admin.support.replyPlaceholder': 'اكتب ردك...',
    'admin.support.send': 'إرسال',
    'admin.support.noConvos': 'لا توجد محادثات بعد',
    'admin.support.admin': 'المدير',
    'admin.support.support': 'الدعم',

    // Admin Roles
    'admin.roles.title': 'إدارة الأدوار',
    'admin.roles.subtitle': 'تعيين وإدارة أدوار المستخدمين: المحلل، الدعم، مدير المفاتيح، وصلاحيات الدعم',
    'admin.roles.assignRole': 'تعيين دور',
    'admin.roles.assignToUser': 'تعيين دور لمستخدم',
    'admin.roles.selectUser': 'اختر المستخدم',
    'admin.roles.selectRole': 'اختر الدور',
    'admin.roles.coreRoles': 'الأدوار الأساسية',
    'admin.roles.supportPerms': 'صلاحيات الدعم',
    'admin.roles.allAssignments': 'جميع تعيينات الأدوار',
    'admin.roles.search': 'بحث...',
    'admin.roles.noAssignments': 'لا توجد تعيينات أدوار',
    'admin.roles.user': 'المستخدم',
    'admin.roles.role': 'الدور',
    'admin.roles.assignedAt': 'تاريخ التعيين',
    'admin.roles.assignedBy': 'عيّنه',
    'admin.roles.remove': 'إزالة',
    'admin.roles.usersWithRole': 'مستخدم لديه هذا الدور',
    'admin.roles.analyst': 'المحلل',
    'admin.roles.support': 'الدعم',
    'admin.roles.keyManager': 'مدير المفاتيح',
    'admin.roles.viewProgress': 'عرض التقدم',
    'admin.roles.viewRec': 'عرض التوصيات',
    'admin.roles.viewSubs': 'عرض الاشتراكات',
    'admin.roles.viewQuizzes': 'عرض الاختبارات',
    'admin.roles.clientLookup': 'البحث عن العملاء',

    // Admin Quiz
    'admin.quiz.dashboard': 'لوحة إدارة الاختبارات',
    'admin.quiz.dashSubtitle': 'مراقبة أداء الاختبارات في جميع المستويات',
    'admin.quiz.userProgress': 'تقدم الطلاب',
    'admin.quiz.manageQuestions': 'إدارة الأسئلة',
    'admin.quiz.analytics': 'التحليلات',
    'admin.quiz.totalAttempts': 'إجمالي المحاولات',
    'admin.quiz.activeUsers': 'المستخدمون النشطون',
    'admin.quiz.avgScore': 'متوسط النتيجة',
    'admin.quiz.passRate': 'نسبة النجاح',
    'admin.quiz.performByLevel': 'الأداء حسب المستوى',
    'admin.quiz.level': 'المستوى',
    'admin.quiz.attempts': 'المحاولات',
    'admin.quiz.passed': 'ناجح',
    'admin.quiz.avgScoreLabel': 'متوسط النتيجة',
    'admin.quiz.passRateLabel': 'نسبة النجاح',
    'admin.quiz.difficultQs': 'الأسئلة الصعبة',
    'admin.quiz.question': 'السؤال',
    'admin.quiz.wrongAnswers': 'إجابات خاطئة',
    'admin.quiz.recentActivity': 'النشاط الأخير',
    'admin.quiz.user': 'المستخدم',
    'admin.quiz.score': 'النتيجة',
    'admin.quiz.result': 'النتيجة',
    'admin.quiz.date': 'التاريخ',
    'admin.quiz.passedBadge': 'ناجح',
    'admin.quiz.failedBadge': 'راسب',
    'admin.quiz.editQuestion': 'تعديل السؤال',
    'admin.quiz.usersTitle': 'مراقبة تقدم الطلاب',
    'admin.quiz.usersSubtitle': 'تتبع أداء الطلاب في الاختبارات',
    'admin.quiz.backToDash': 'العودة للوحة',
    'admin.quiz.searchUsers': 'بحث بالاسم أو البريد...',
    'admin.quiz.totalUsers': 'إجمالي المستخدمين',
    'admin.quiz.completedAll': 'أكملوا جميع المستويات',
    'admin.quiz.allUsers': 'جميع المستخدمين',
    'admin.quiz.unlocked': 'مفتوح',
    'admin.quiz.bestScores': 'أفضل النتائج',
    'admin.quiz.lastActivity': 'آخر نشاط',
    'admin.quiz.questionsTitle': 'إدارة الأسئلة',
    'admin.quiz.questionsSubtitle': 'تعديل أسئلة وإجابات الاختبارات',
    'admin.quiz.editGuidelines': 'إرشادات التعديل:',
    'admin.quiz.guideline1': 'اضغط على أي سؤال لتعديله',
    'admin.quiz.guideline2': 'حدد الإجابات الصحيحة باستخدام مربعات الاختيار',
    'admin.quiz.guideline3': 'يتم حفظ التغييرات فورًا',
    'admin.quiz.questionText': 'نص السؤال',
    'admin.quiz.answerOptions': 'خيارات الإجابة (حدد الإجابات الصحيحة)',
    'admin.quiz.saveChanges': 'حفظ التغييرات',
    'admin.quiz.cancelEdit': 'إلغاء',
    'admin.quiz.questions': 'سؤال',

    // Analytics & Settings (placeholder pages)
    'admin.analytics.title': 'لوحة التحليلات',
    'admin.analytics.subtitle': 'عرض الإحصائيات والمؤشرات',
    'admin.analytics.comingSoon': 'لوحة التحليلات – قريبًا',
    'admin.analytics.revenue': 'تتبع الإيرادات واتجاهات الاشتراكات',
    'admin.analytics.userGrowth': 'مراقبة نمو المستخدمين والتفاعل',
    'admin.analytics.totalRevenue': 'إجمالي الإيرادات',
    'admin.analytics.activeUsers': 'المستخدمون النشطون',
    'admin.analytics.courseCompletions': 'الدورات المكتملة',
    'admin.analytics.flexaiUsage': 'استخدام FlexAI',

    'admin.settings.title': 'الإعدادات',
    'admin.settings.subtitle': 'إدارة إعدادات المنصة',
    'admin.settings.comingSoon': 'لوحة الإعدادات – قريبًا',
    'admin.settings.notifications': 'الإشعارات',
    'admin.settings.notifDesc': 'تفضيلات الإشعارات',
    'admin.settings.security': 'الأمان',
    'admin.settings.secDesc': 'إعدادات الأمان والمصادقة',
    'admin.settings.email': 'إعدادات البريد',
    'admin.settings.emailDesc': 'إعداد البريد الإلكتروني والقوالب',
    'admin.settings.database': 'قاعدة البيانات',
    'admin.settings.dbDesc': 'إدارة قاعدة البيانات والنسخ الاحتياطي',

    'admin.enrollments.title': 'التسجيلات',
    'admin.enrollments.subtitle': 'تتبع تسجيلات الطلاب',
    'admin.enrollments.comingSoon': 'تتبع التسجيلات – قريبًا',
    'admin.enrollments.viewAll': 'عرض جميع تسجيلات الطلاب',
    'admin.enrollments.certificates': 'إنشاء شهادات الإكمال',
    'admin.enrollments.what': 'ما هي التسجيلات؟',
    'admin.enrollments.total': 'إجمالي التسجيلات',
    'admin.enrollments.activeStudents': 'الطلاب النشطون',
    'admin.enrollments.completionRate': 'نسبة الإكمال',

    // Common admin strings
    'admin.loading': 'جار التحميل...',
    'admin.comingSoon': 'قريبًا',
    'admin.unknown': 'غير معروف',

    // Additional Dashboard keys
    'admin.dashboard.keysDesc': 'إنشاء وإدارة مفاتيح تسجيل الدورات',
    'admin.dashboard.coursesDesc': 'عرض وإدارة جميع الدورات والحلقات',
    'admin.dashboard.usersDesc': 'إدارة المستخدمين والتسجيلات',
    'admin.totalEnrollments': 'إجمالي التسجيلات',

    // Additional Users page keys
    'admin.users.allUsersDesc': 'جميع المستخدمين الذين أنشأوا حسابات',
    'admin.users.courseEnrollments': 'تسجيلات الدورات',
    'admin.users.enrollmentsDesc': 'جميع التسجيلات وحالتها',
    'admin.users.lastSignIn': 'آخر تسجيل دخول',
    'admin.users.user': 'المستخدم',
    'admin.users.course': 'الدورة',
    'admin.users.progress': 'التقدم',
    'admin.users.payment': 'الدفع',
    'admin.users.status': 'الحالة',
    'admin.users.enrolled': 'التسجيل',
    'admin.users.noUsers': 'لا يوجد مستخدمين بعد',
    'admin.users.noEnrollments': 'لا يوجد تسجيلات بعد',
    'admin.users.currentlyActive': 'نشط حالياً',
    'admin.users.enrollmentsSub': 'تسجيلات الدورات',
    'admin.users.allTimeRevenue': 'إجمالي الإيرادات',

    // Additional Courses page keys
    'admin.courses.saving': 'جار الحفظ...',
    'admin.courses.update': 'تحديث',
    'admin.courses.create': 'إنشاء',
    'admin.courses.deleteConfirm': 'هل أنت متأكد من حذف هذه الدورة؟ سيتم حذف جميع الحلقات والتسجيلات.',
    'admin.courses.noCoursesCta': 'أنشئ أول دورة للبدء!',
    'admin.courses.thumbnail.label': 'صورة الدورة',

    // Additional Episodes page keys
    'admin.episodes.invalidCourse': 'معرف الدورة غير صالح',
    'admin.episodes.createFirstDesc': 'أنشئ أول حلقة لبدء بناء محتوى الدورة',
    'admin.episodes.freePreview': 'معاينة مجانية',
    'admin.episodes.premium': 'مدفوع',
    'admin.episodes.saving': 'جار الحفظ...',
    'admin.episodes.update': 'تحديث',
    'admin.episodes.create': 'إنشاء',
    'admin.episodes.deleteConfirm': 'هل أنت متأكد من حذف هذه الحلقة؟',
    'admin.episodes.fillBoth': 'أدخل بيانات الحلقة بالإنجليزية والعربية',

    // Additional Keys page keys
    'admin.keys.manageCourseAccess': 'إدارة مفاتيح وصول الدورات للطلاب',
    'admin.keys.createKeyDesc': 'إنشاء مفتاح تسجيل جديد لدورة',
    'admin.keys.bulkTitle': 'إنشاء مفاتيح بالجملة',
    'admin.keys.bulkDesc': 'إنشاء عدة مفاتيح تسجيل دفعة واحدة (الحد الأقصى 1000)',
    'admin.keys.notActivated': 'غير مفعل',
    'admin.keys.created': 'تاريخ الإنشاء',
    'admin.keys.generating': 'جار الإنشاء...',
    'admin.keys.searchByEmail': 'بحث بالبريد...',
    'admin.keys.email': 'البريد',

    // Additional LexAI keys
    'admin.lexai.generateKey': 'إنشاء مفتاح',
    'admin.lexai.generateSingle': 'إنشاء مفتاح واحد',
    'admin.lexai.createKeyDesc': 'إنشاء مفتاح وصول LexAI جديد',
    'admin.lexai.bulkGenerate': 'إنشاء دفعة',
    'admin.lexai.bulkTitle': 'إنشاء مفاتيح بالجملة',
    'admin.lexai.bulkDesc': 'إنشاء عدة مفاتيح LexAI دفعة واحدة (الحد الأقصى 1000)',
    'admin.lexai.exportCsv': 'تصدير',
    'admin.lexai.notesLabel': 'ملاحظات (اختياري)',
    'admin.lexai.notesPlaceholder': 'أضف ملاحظات حول هذا المفتاح...',
    'admin.lexai.quantity': 'الكمية',
    'admin.lexai.generating': 'جار الإنشاء...',
    'admin.lexai.generateKeys': 'إنشاء المفاتيح',
    'admin.lexai.key': 'المفتاح',
    'admin.lexai.created': 'تاريخ الإنشاء',
    'admin.lexai.used': 'مستخدم',
    'admin.lexai.notes': 'ملاحظات',
    'admin.lexai.noKeys': 'لا توجد مفاتيح',
    'admin.lexai.available': 'متاح',
    'admin.lexai.deactivated': 'معطل',
    'admin.lexai.activated': 'مفعل',
    'admin.lexai.totalKeys': 'إجمالي المفاتيح',
    'admin.lexai.unusedKeys': 'غير مستخدمة',
    'admin.lexai.deactivatedKeys': 'معطلة',
    'admin.lexai.clickToView': 'اضغط على مستخدم لعرض سجل محادثاته',
    'admin.lexai.loadingMessages': 'جار تحميل الرسائل...',
    'admin.lexai.noMessages': 'لا توجد رسائل',

    // Additional Roles keys
    'admin.roles.email': 'البريد',
    'admin.roles.actions': 'إجراءات',
    'admin.roles.assigning': 'جار التعيين...',
    'admin.roles.userLabel': 'مستخدم لديه هذا الدور',

    // Additional Quiz keys
    'admin.quiz.loadingStats': 'جار تحميل الإحصائيات...',
    'admin.quiz.loadingUsers': 'جار تحميل المستخدمين...',
    'admin.quiz.loadingQuestions': 'جار تحميل الأسئلة...',
    'admin.quiz.failedToLoad': 'فشل تحميل البيانات',
    'admin.quiz.viewStudents': 'عرض جميع الطلاب',
    'admin.quiz.editContent': 'تعديل محتوى الاختبار',
    'admin.quiz.detailedReports': 'تقارير تفصيلية',
    'admin.quiz.title': 'العنوان',
    'admin.quiz.completion': 'الإكمال',
    'admin.quiz.lowestCorrectRate': 'الأسئلة ذات أقل نسبة صحة',
    'admin.quiz.correctPct': 'صحيح',
    'admin.quiz.latestAttempts': 'أحدث محاولات الاختبار',
    'admin.quiz.noData': 'لا توجد بيانات بعد',
    'admin.quiz.noActivity': 'لا يوجد نشاط بعد',
    'admin.quiz.noUsersFound': 'لا يوجد مستخدمين يطابقون البحث',
    'admin.quiz.noUsers': 'لا يوجد مستخدمين بعد',
    'admin.quiz.completed': 'مكتمل',
    'admin.quiz.resetProgress': 'إعادة تعيين التقدم',
    'admin.quiz.viewDetails': 'عرض التفاصيل',
    'admin.quiz.saving': 'جار الحفظ...',
    'admin.quiz.correctRate': 'نسبة الصحة',
    'admin.quiz.attempted': 'المحاولات',
    'admin.quiz.times': 'مرة',

    // Additional Analytics keys
    'admin.analytics.building': 'نحن نبني ميزات تحليلات قوية لك',
    'admin.analytics.underDev': 'لوحة التحليلات قيد التطوير حاليًا. قريبًا ستتمكن من:',
    'admin.analytics.viewCompletionRates': 'عرض معدلات إكمال الدورات',
    'admin.analytics.analyzeUsage': 'تحليل إحصائيات استخدام FlexAI',
    'admin.analytics.revenueTracking': 'تتبع الإيرادات',
    'admin.analytics.userAnalytics': 'تحليلات المستخدمين',
    'admin.analytics.courseMetrics': 'مقاييس الدورات',
    'admin.analytics.aiAnalytics': 'تحليلات الذكاء الاصطناعي',

    // Additional Settings keys
    'admin.settings.advancedDev': 'خيارات الإعداد المتقدمة قيد التطوير',
    'admin.settings.underDev': 'لوحة الإعدادات قيد التطوير حاليًا. قريبًا ستتمكن من إعداد:',
    'admin.settings.notifPref': 'تفضيلات الإشعارات',
    'admin.settings.secSettings': 'إعدادات الأمان والمصادقة',
    'admin.settings.emailTemplates': 'قوالب البريد الإلكتروني والإشعارات',
    'admin.settings.dbBackup': 'النسخ الاحتياطي وصيانة قاعدة البيانات',
    'admin.settings.configNotif': 'إعداد تفضيلات الإشعارات',
    'admin.settings.manageSecurity': 'إدارة إعدادات الأمان',
    'admin.settings.configEmail': 'إعداد قوالب البريد',
    'admin.settings.dbMaintenance': 'خيارات صيانة قاعدة البيانات',

    // Additional Enrollments keys
    'admin.enrollments.trackDesc': 'تتبع تسجيلات الطلاب وتقدم الدورات',
    'admin.enrollments.devDesc': 'ميزات تتبع تقدم الطلاب قيد التطوير',
    'admin.enrollments.underDev': 'نظام تتبع التسجيلات قيد التطوير حاليًا. قريبًا ستتمكن من:',
    'admin.enrollments.trackProgress': 'تتبع تقدم الدورات والإكمال',
    'admin.enrollments.monitorEngagement': 'مراقبة مقاييس تفاعل الطلاب',
    'admin.enrollments.whatDesc': 'فهم نظام التسجيلات',
    'admin.enrollments.whatText': 'التسجيلات تتبع الطلاب المسجلين في الدورات وتقدمهم في المحتوى.',
    'admin.enrollments.keyFeatures': 'الميزات الرئيسية (عند التنفيذ):',
    'admin.enrollments.feature1': 'تتبع المستخدمين المسجلين في الدورات',
    'admin.enrollments.feature2': 'مراقبة تقدم مشاهدة الفيديو',
    'admin.enrollments.feature3': 'عرض معدلات الإكمال لكل دورة',
    'admin.enrollments.feature4': 'تحديد الطلاب المتعثرين الذين يحتاجون مساعدة',
    'admin.enrollments.feature5': 'إنشاء تقارير حول أداء الطلاب',
    'admin.enrollments.note': 'حالياً، يتم إدارة الوصول للدورات عبر مفاتيح التسجيل. سيوفر نظام تتبع التسجيلات رؤى أعمق حول تقدم الطلاب.',
    'admin.enrollments.studentEnrollments': 'تسجيلات الطلاب',
    'admin.enrollments.currentlyLearning': 'يتعلمون حالياً',
    'admin.enrollments.averageCompletion': 'متوسط الإكمال',

    // Auth Pages
    'auth.login.title': 'مرحبًا بعودتك',
    'auth.login.description': 'سجل الدخول لمتابعة التعلم',
    'auth.login.adminTitle': 'تسجيل دخول المسؤول',
    'auth.login.adminDescription': 'سجل الدخول للوصول إلى لوحة الإدارة',
    'auth.login.email': 'البريد الإلكتروني',
    'auth.login.password': 'كلمة المرور',
    'auth.login.emailPlaceholder': 'john@example.com',
    'auth.login.passwordPlaceholder': '••••••••',
    'auth.login.submit': 'تسجيل الدخول',
    'auth.login.submitting': 'جاري تسجيل الدخول...',
    'auth.login.allFieldsRequired': 'جميع الحقول مطلوبة',
    
    'auth.register.title': 'إنشاء حساب',
    'auth.register.description': 'سجل للبدء في تعلم التداول',
    'auth.register.fullName': 'الاسم الكامل',
    'auth.register.email': 'البريد الإلكتروني',
    'auth.register.password': 'كلمة المرور',
    'auth.register.confirmPassword': 'تأكيد كلمة المرور',
    'auth.register.namePlaceholder': 'أحمد محمد',
    'auth.register.emailPlaceholder': 'ahmad@example.com',
    'auth.register.passwordPlaceholder': '••••••••',
    'auth.register.passwordHint': 'على الأقل 8 أحرف مع حرف كبير وحرف صغير ورقم واحد',
    'auth.register.submit': 'إنشاء حساب',
    'auth.register.submitting': 'جاري إنشاء الحساب...',
    'auth.register.allFieldsRequired': 'جميع الحقول مطلوبة',
    'auth.register.passwordMismatch': 'كلمات المرور غير متطابقة',
    'auth.register.passwordTooShort': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    
    'auth.page.backToHome': '→ العودة إلى الصفحة الرئيسية',
    'auth.page.tagline': 'أتقن فن التداول',
    'auth.page.switchToRegister': 'ليس لديك حساب؟',
    'auth.page.switchToLogin': 'هل لديك حساب بالفعل؟',
    'auth.page.signUp': 'سجل',
    'auth.page.signIn': 'تسجيل الدخول',
    
    // Profile Page
    'profile.title': 'إعدادات الحساب',
    'profile.description': 'إدارة ملفك الشخصي وإعدادات الأمان',
    'profile.backToDashboard': 'العودة إلى لوحة التحكم',
    'profile.email': 'البريد الإلكتروني',
    'profile.emailReadonly': 'لا يمكن تغيير البريد الإلكتروني',
    'profile.name': 'الاسم الكامل',
    'profile.nameplaceholder': 'أدخل اسمك الكامل',
    'profile.phone': 'رقم الهاتف',
    'profile.phoneExample': '+966 50 000 0000',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.updating': 'جاري الحفظ...',
    'profile.cancel': 'إلغاء',
    'profile.updates.success': 'تم تحديث الملف الشخصي بنجاح',
    'profile.error': 'خطأ',
    
    'profile.profileInfo.title': 'معلومات الملف الشخصي',
    'profile.profileInfo.description': 'حدث معلوماتك الشخصية',
    
    'profile.security.title': 'الأمان',
    'profile.security.description': 'إدارة كلمة المرور والإعدادات الأمنية',
    'profile.password.change': 'تغيير كلمة المرور',
    'profile.password.current': 'كلمة المرور الحالية',
    'profile.password.new': 'كلمة المرور الجديدة',
    'profile.password.confirm': 'تأكيد كلمة المرور الجديدة',
    'profile.password.enterCurrent': 'أدخل كلمة المرور الحالية',
    'profile.password.enterNew': 'أدخل كلمة المرور الجديدة',
    'profile.password.confirmNew': 'أكد كلمة المرور الجديدة',
    'profile.password.requirements': 'الحد الأدنى 8 أحرف مع أحرف كبيرة وصغيرة وأرقام',
    'profile.password.allFieldsRequired': 'جميع حقول كلمة المرور مطلوبة',
    'profile.password.mismatch': 'كلمات المرور الجديدة غير متطابقة',
    'profile.password.tooShort': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    'profile.password.changed': 'تم تغيير كلمة المرور بنجاح',
    'profile.password.update': 'تحديث كلمة المرور',
    'profile.password.updating': 'جاري تحديث كلمة المرور...',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.create': 'إنشاء',
    'common.back': 'رجوع',

    // Support Chat
    'support.title': 'الدعم الفني',
    'support.subtitle': 'نحن هنا لمساعدتك',
    'support.empty': 'لا توجد رسائل بعد',
    'support.emptyHint': 'أرسل رسالة لبدء محادثة مع فريق الدعم',
    'support.placeholder': 'اكتب رسالتك...',
    'support.agent': 'الدعم',
    'support.admin': 'المدير',

    // Recommendations Page
    'rec.title': 'قروب التوصيات',
    'rec.subtitle': 'تنبيهات وتوصيات مباشرة مع إمكانية نسخ سريع للتنفيذ',
    'rec.accessStatus': 'حالة الوصول',
    'rec.accessDesc': 'اشتراك قروب التوصيات منفصل عن الدورة و LexAI',
    'rec.checking': 'جاري التحقق...',
    'rec.status': 'الحالة',
    'rec.activated': 'مفعل',
    'rec.notActivated': 'غير مفعل',
    'rec.expiryDate': 'تاريخ الانتهاء',
    'rec.enterKey': 'أدخل مفتاح التوصيات',
    'rec.activateKey': 'تفعيل المفتاح',
    'rec.publishNew': 'نشر توصية جديدة',
    'rec.publishDesc': 'مخصص للمحلل/الموظف المسؤول عن القروب',
    'rec.typeAlert': 'تنبيه',
    'rec.typeRecommendation': 'توصية',
    'rec.typeResult': 'نتيجة',
    'rec.symbolPlaceholder': 'الزوج/الأصل (اختياري)',
    'rec.sidePlaceholder': 'الاتجاه BUY/SELL (اختياري)',
    'rec.entryPlaceholder': 'سعر الدخول (اختياري)',
    'rec.slPlaceholder': 'وقف الخسارة (اختياري)',
    'rec.tp1Placeholder': 'الهدف الأول (اختياري)',
    'rec.tp2Placeholder': 'الهدف الثاني (اختياري)',
    'rec.riskPlaceholder': 'نسبة المخاطرة (اختياري)',
    'rec.messagePlaceholder': 'اكتب التوصية أو النتيجة هنا...',
    'rec.publishBtn': 'نشر + إرسال إيميل',
    'rec.messages': 'الرسائل',
    'rec.messagesDesc': 'تحديثات القروب بشكل مباشر',
    'rec.loadingMessages': 'جاري تحميل الرسائل...',
    'rec.noMessages': 'لا توجد رسائل بعد.',
    'rec.analyst': 'محلل',
    'rec.copy': 'نسخ',
    'rec.toastKeyActivated': 'تم تفعيل مفتاح قروب التوصيات بنجاح',
    'rec.toastPublished': 'تم نشر الرسالة وإرسال الإشعارات',
    'rec.toastEnterKey': 'يرجى إدخال المفتاح',
    'rec.toastWriteMessage': 'الرجاء كتابة الرسالة',
    'rec.toastCopied': 'تم نسخ التوصية',
    'rec.copySymbol': 'الزوج/الأصل',
    'rec.copySide': 'الاتجاه',
    'rec.copyEntry': 'الدخول',
    'rec.copySL': 'وقف الخسارة',
    'rec.copyTP1': 'هدف 1',
    'rec.copyTP2': 'هدف 2',
    'rec.copyRisk': 'نسبة المخاطرة',

    // CourseWatch Page
    'course.loading': 'جاري تحميل الدورة...',
    'course.notFound': 'الدورة غير موجودة',
    'course.backHome': 'العودة للرئيسية',
    'course.signInRequired': 'تسجيل الدخول مطلوب',
    'course.signInToAccess': 'يرجى تسجيل الدخول للوصول إلى هذه الدورة',
    'course.signInBtn': 'تسجيل الدخول للمتابعة',
    'course.enrollRequired': 'التسجيل مطلوب',
    'course.enrollDesc': 'يجب التسجيل في هذه الدورة للوصول إلى المحتوى',
    'course.oneTimePayment': 'دفعة واحدة',
    'course.enrollNow': 'سجل الآن',
    'course.progress': 'التقدم',
    'course.episode': 'حلقة',
    'course.free': 'مجاني',
    'course.markComplete': 'تحديد كمكتمل',
    'course.nextEpisode': 'الحلقة التالية',
    'course.watchProgress': 'تقدم المشاهدة',
    'course.required': 'مطلوب',
    'course.episodeQuiz': 'اختبار الحلقة',
    'course.quizDesc': 'أجب بنسبة 50% على الأقل لفتح إكمال هذه الحلقة.',
    'course.loadingQuiz': 'جاري تحميل الاختبار...',
    'course.noQuiz': 'لم يتم إعداد اختبار لهذه الحلقة بعد.',
    'course.quizPassed': 'تم اجتياز الاختبار. يمكنك الآن تحديد هذه الحلقة كمكتملة.',
    'course.submitQuiz': 'إرسال الاختبار',
    'course.score': 'النتيجة',
    'course.requiredScore': 'المطلوب',
    'course.aboutCourse': 'عن هذه الدورة',
    'course.level': 'المستوى',
    'course.episodes': 'الحلقات',
    'course.courseProgress': 'تقدم الدورة',
    'course.ofEpisodes': 'من',
    'course.episodesCompleted': 'حلقة مكتملة',
    'course.percentComplete': 'مكتمل',
    'course.min': 'دقيقة',
    'course.toastCompleted': 'تم تحديد الحلقة كمكتملة!',
    'course.toastCompleteFail': 'تعذر تحديد الحلقة كمكتملة',
    'course.toastAnswerAll': 'يرجى الإجابة على جميع الأسئلة',
    'course.toastUnlockPrev': 'أكمل الحلقات السابقة لفتح هذه الحلقة.',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get language from localStorage or default to Arabic
    const saved = localStorage.getItem('language');
    return (saved === 'ar' || saved === 'en') ? saved : 'ar';
  });

  useEffect(() => {
    // Save language preference
    localStorage.setItem('language', language);
    
    // Update document direction and lang attribute
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
